name: "setup-cf"
author: "Christopher Banck"
description: "Setup Cloud Foundry CLI environment."
branding:
  icon: "upload-cloud"
  color: "blue"
inputs:
  api:
    description: "Url of the cloud controller api"
    required: true
  client_assertion:
    description: "client assertion for requesting token"
    required: true
  client_id:
    description: "client id"
    required: false
  client_secret:
    description: "client secret"
    required: false
  command:
    description: "run cf command"
    required: false
  grant_type:
    description: "grant type for requesting token"
    required: true
    default: "password"
  id_token:
    description: "id_token for JWT Bearer Token Grant"
    required: false
  username:
    description: "username"
    required: false
  password:
    description: "password"
    required: false
  org:
    description: "org"
    required: false
  space:
    description: "space"
    required: false
  version:
    description: "cf cli version"
    required: true
    default: "8.7.10"
  zone:
    description: "zone name"
    required: false
    default: "uaa"
runs:
  using: "node20"
  main: "dist/index.js"
